### ISSUE TITLE
DB updates in background not reflected

### ISSUE THREAD

**Issue by recnac** [cloudant/python-cloudant#111]
Maybe I am holding it wrong, but are updates done to the DB reflected in an open DB connection?
I have this test snippet.

    import time
    from cloudant.account import Cloudant
    cloudantCredentials = {
    	"username": "HOST",
    	"password": "USERNAME",
    	"host": "PASSWORD"
    }
    db = Cloudant(cloudantCredentials["username"], cloudantCredentials["password"], url=cloudantCredentials["host"])
    db.connect()
    while True:
    	print(db["testTable"]["testDocument"]["testProperty"])
    	time.sleep(5) 

When I run it and then do changes to the document i would expect the console output to change. Instead it stays the same. Is this expected behavior and is there some kind of update function I can trigger to get in sync with the remote DB? Building a new connection/session every time a request hits largely impacts response times.

**Comment by alfinkel** [comment]
A few comments...

It looks to me like you are trying to capture changes made in a database.  If that is the case then I recommend using the [changes](http://python-cloudant.readthedocs.org/en/latest/database.html#cloudant.database.CouchDatabase.changes) convenience method on the database object.

Now addressing your question directly, it appears that what you refer to as your `db` variable is really your Cloudant account client which in turn can contain many Cloudant databases.  Your actual database is referenced by `db["testTable"]`.  Anyway, when you "get" a database object from the client, the default behavior is to only get the the database remotely if it does not exist in the local cache of the client.  Otherwise the database object is retrieved from the local cache which is what you are seeing.  To force a remote "get" you could change your code to `print(db.get("testTable", remote=True)["testDocument"]["testProperty"])`.  This will retrieve a new version of the "testTable" database each time the code is executed and in turn it will clear out the local database cache which will force the document "testDocument" to be retrieved remotely everytime that line of code is executed.  

Another, more direct way to do the same would be to do something like this:

```python
import time
from cloudant.account import Cloudant
cloudantCredentials = {
    "username": "HOST",
    "password": "USERNAME",
    "host": "HOST"
}
client = Cloudant(cloudantCredentials["username"], cloudantCredentials["password"], url=cloudantCredentials["host"])
client.connect()
db = client['testTable']
doc = db['testDocument']
while True:
    doc.fetch()
    print(doc["testProperty"])
    time.sleep(5)
```

Since it is the refreshed document you are really interested in, the document `.fetch()` call allows you to control the fetching of the document directly without having to deal with refreshing the client local cache which in turn forces the refesh of every object in the client -> db -> document hierarchy.

Anyway,  hope that helps.

**Comment by recnac** [comment]
You are my hero. Thanks.
