### ISSUE TITLE
Update readthedocs link in README.rst

### ISSUE THREAD

**Issue by alfinkel** [cloudant/python-cloudant#161]
The current link to the library documentation in the README.rst is set to `http://python-cloudant.readthedocs.org`.  This resolves to `http://python-cloudant.readthedocs.org/index.html` which is actually our index module documentation.  When a user clicks this link we want it to go to the documentation home page which is currently `default.html`.  We may want to consider either changing the link to specifically point to `http://python-cloudant.readthedocs.org/default.html` or renaming index.html to something different and renaming default.html to index.html.

**Comment by ricellis** [comment]
See also #155 if we're updating doc links.

**Comment by emlaver** [comment]
The links are still pointing to the index module `index.html` in these and probably other locations:
- Github `Cloudant Python client library docs (readthedocs.io)` link under `Related Documentation`
- Links under `Short URLs` header: https://readthedocs.org/projects/python-cloudant/

Another PR will be opened to fix this.  The `default.html` will be renamed to `index.html` so that `http://python-cloudant.readthedocs.io` will resolve to the library documentation home page.  The current `index.html` containing index module documentation will be renamed to `module_index.html` or something similar.
