### ISSUE TITLE
I am facing strange ArgumentError of Cloudant.

### ISSUE THREAD

**Issue by takara9** [cloudant/python-cloudant#165]
Hello,
I tried to create a index by this package. but, I am facing strange Cloudant ArgumentError.

- Cloudant (python-cloudant) version(s) that are affected by this issue.
$ pip freeze
cloudant==2.0.0

- Python version 
$ python --version
Python 2.7.10

- A small code sample that demonstrates the issue.
--- case 1 code ---
~~~
ix = Index(db,                                                                                                 
            design_document_id="nlc_index",                                                                     
            index_name="idx_l2_class",                                                                          
            index_type="text",                                                                                  
            fields=[{'name': 'l2_class', 'type': 'string'}])                                                    
ix.create()
~~~

in this case, I got this following error.
~~~
Traceback (most recent call last):
  File "./create_nlc_database.py", line 77, in <module>
    idx.create()
  File "/home/tkr/.pyenv/versions/2.7.10/lib/python2.7/site-packages/cloudant/index.py", line 141, in create
    self._def_check()
  File "/home/tkr/.pyenv/versions/2.7.10/lib/python2.7/site-packages/cloudant/index.py", line 164, in _def_check
    raise CloudantArgumentError(msg)
cloudant.error.CloudantArgumentError: {'fields': [{'type': 'string', 'name': 'l2_class'}], 'index_name': 'idx_l2_class', 'index_type': 'text'} provided as argument(s).  A JSON index requires that only a 'fields' argument is provided.
~~~

so, I change my python code to determine problem.
--- case 2 new code ---
~~~
ix = Index(db,
            fields=[{'name': 'l2_class', 'type': 'string'},{'name': 'csv', 'type': 'string'}])
ix.create()
~~~

The error message was changed in following.
~~~
Traceback (most recent call last):
  File "./create_nlc_database.py", line 85, in <module>
    idx.create()
  File "/home/tkr/.pyenv/versions/2.7.10/lib/python2.7/site-packages/cloudant/index.py", line 150, in create
    resp.raise_for_status()
  File "/home/tkr/.pyenv/versions/2.7.10/lib/python2.7/site-packages/requests/models.py", line 840, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://e73ea080-3feb-42c2-993f-3104142de7e9-bluemix:b6fa998abf11e61e8d64fc23e271d3692f1680214cd3ccaa569a9da000f5714d@e73ea080-3feb-42c2-993f-3104142de7e9-bluemix.cloudant.com/nlc_name_database/_index
~~~
How do I avoid this issue ?

Thans !
Maho

**Comment by alfinkel** [comment]
The reason for the `CloudantArgumentError` is because you are trying to create a text index with the JSON index class.  See [here](http://python-cloudant.readthedocs.io/en/latest/index.html#cloudant.index.Index).  An `Index` constructor does not take `index_type` as an argument so even though you set it in your code, the constructor ignores it but the error is raised when you try to do something like creating the index since it does not expect to see an `index_type`.

My suggestion is to use the `CouchDatabase` convenience method [create_query_index](http://python-cloudant.readthedocs.io/en/latest/database.html#cloudant.database.CloudantDatabase.create_query_index) which will allow you to provide an index_type and create either a JSON or a text index and will return the appropriate object (`Index` or `TextIndex`).

If your index already exists in the database then my suggestion is to use the `CouchDatabase` convenience method [get_query_indexes](https://github.com/cloudant/python-cloudant/blob/master/src/cloudant/database.py#L898) which will return a list of the query indexes as their appropriate objects (`Index`, `TextIndex`, `SpecialIndex`).

Some useful documentation references:

- [Create a query index](http://python-cloudant.readthedocs.io/en/latest/database.html#cloudant.database.CloudantDatabase.create_query_index)
- [Retrieve query indexes](http://python-cloudant.readthedocs.io/en/latest/database.html#cloudant.database.CloudantDatabase.get_query_indexes)
- [Remove a query index](http://python-cloudant.readthedocs.io/en/latest/database.html#cloudant.database.CloudantDatabase.delete_query_index)
- [Run a query](http://python-cloudant.readthedocs.io/en/latest/database.html#cloudant.database.CloudantDatabase.get_query_result)

I hope this helps.

**Comment by alfinkel** [comment]
Small update to my previous comment:  The suggested convenience methods are found in the `CloudantDatabase` and not the `CouchDatabase`.  The previous comment has been edited for correctness.

**Comment by alfinkel** [comment]
Closing since the question was answered and the `CloudantArgumentError` was deemed to be appropriate behavior.  We can reopen the issue if necessary.
