### ISSUE TITLE
User-Agent not being set on Couch contexts

### ISSUE THREAD

**Issue by ricellis** [cloudant/python-cloudant#173]
The User-Agent header is not being set as expected. Using the example below I see the User-Agent header on my request as `python-requests/2.10.0` not the expected `python-cloudant/2.0.0/Python/2.7.11/Darwin/x86_64`

The agent is as expected when using the Cloudant client context, just not the CouchDB context.
- Cloudant (python-cloudant) version(s) that are affected by this issue.
  2.0.0
- Python version
  2.7.11
- A small code sample that demonstrates the issue.

``` python
from cloudant import couchdb_admin_party

with couchdb_admin_party(url='http://localhost:5984') as client:
  print 'Databases: {0}'.format(client.all_dbs())
```

**Comment by alfinkel** [comment]
I think this is by design.  The `couchdb_admin_party` context manager stands up a CouchDB client which does not set the User-Agent header.  Only a Cloudant client currently sets the User-Agent to what you are expecting to see.  So, if you use a `cloudant` context manager you should see the expected User-Agent header.  What I assume you are seeing is the Python Requests module adding its own User-Agent.

**Comment by ricellis** [comment]
Yeah I did see it was only set for Cloudant, but I didn't understand why we didn't use the same User-Agent for all requests coming from the lib. It is an identifier for the library so why not always use it?

**Comment by alfinkel** [comment]
I think the purpose of the header was to provide us with details for requests coming in to Cloudant not to serve as an identifier for the library as a whole.  Based on the original intent of the User-Agent, at least in this library, I don't see the benefit of setting the header for CouchDB clients since I can't imagine who would be looking at it.  I was however, unaware that it was being set by the Requests module.  Anyway, obviously it would not be a monumental effort to move the logic there instead and probably wouldn't hurt anything.

**Comment by ricellis** [comment]
Sorry I gave the issue an unclear title and I agree it is probably of limited use, but I guess I just expected it on all requests out of the lib.

**Comment by ricellis** [comment]
Won't change. Our new [cloudant-python-sdk](https://github.com/IBM/cloudant-python-sdk/)(beta) uses a customized user agent on all requests.
