### ISSUE TITLE
Can't figure out how to get all results with either the Query object or db.get_query_result

### ISSUE THREAD

**Issue by gsellers-ibm** [cloudant/python-cloudant#183]
python-cloudant 2.0.3, Python 2.7.10

I was trying to use the Query object to get results from Cloudant using a text index and found that it only returns the first 200 and you have to use the bookmark argument to get additional pages. Unfortunately, I couldn't figure out how to easily get the bookmarks for different pages in order to select a page of results (I thought at first it was going to be as easy as bookmark = 1,2,3).

So, I started trying to use db.get_query_result on the same text index. It looked like this:
```
test = db.get_query_result(selector=query_object, sort=sort_list,       
                                           limit=limit, skip=skip, page_size=limit)
```
I got some weird results here though. I was messing around with not passing a limit, and setting the page_size to 1000 or 100, but the result was pretty much the same each time.
If I tried getting the length of the results with
```
len(test[:])
```
it always returned 200. If I then did the following
```
new_lst = []
for item in test:
    new_lst.append(item)
print len(new_lst)
```
It returned 600 when I tried get_query_result with no limit and page_size=1000. There were a few thousand docs in the database I was using. If I tried getting specific docs with indexing that were past index 1000 it worked fine (eg. test[1500]) and it seemed to return the appropriate doc.

So, I'm not sure how this is supposed to be working and it's definitely not clear to me from the docs. This seems like a pretty weird result to be getting. Also, it would be much nicer if for both Query and get_query_result there was a simple way to get the total_docs returned rather than having to use len() and bookmarks. Thanks.

**Comment by alfinkel** [comment]
The `page_size` is only used internally when a `Result` or as in this case a `QueryResult` object is iterated over.  `page_size` is how this library provides you the ability to batch your iteration for large data sets so as not to blow out your memory.  Under the covers the `Result` iteration uses `skip` and `limit` to change your initial query to perform this batching.  In other words, if you are iterating over a `Result` you may be making multiple http requests to Cloudant to satisfy the iteration results.  That is why it is generally not a good idea to have `skip` and `limit` inside your query if you plan to iterate over the `Result`.  In fact you should get a raised exception.

`page_size` is meaningless when it comes to `Result` slicing or indexing as in `test[:]` or `test[1500]`.  `Result` slicing also uses `skip` and `limit` but any `Result` slice or `Result` index is only going to make a single http request to Cloudant to get your data.

The difference between using `Query` and the database convenience method `get_query_result` is that `Query` is callable and will return the actual JSON response from your query whereas `get_query_result` by default will return a `Result` object which is a wrapper that tacks on the indexing, slicing, and iteration niceties mentioned earlier.  That `Result` object does not contain the query result initially, all it does is allows you to programmatically manipulate your query so that you can use it Pythonically and then in turn calls the `Query` callable.  You can set `raw_result=True` for `get_query_result` and then it will behave the same as if you called the `Query` callable directly with your query.

If you are looking to use a `bookmark` then you are looking to make multiple separate queries, each as a single request to Cloudant and you are looking to manage the resulting sets of data yourself.  The `bookmark` query parameter is how Cloudant (not this library) provides you the ability to batch your text search results into manageable chunks.  So, in this case using a `Result` object is probably not what you want to be doing.  Instead you should follow the Cloudant documentation on [queries](https://docs.cloudant.com/search.html#queries), use the `raw_result=True` option on `get_query_result`, call it as often as you need to using a different `bookmark` each time and then manage the result sets as necessary.

**Comment by gsellers-ibm** [comment]
Alright that's helpful. Thanks for answering me so quickly.
