### ISSUE TITLE
json.dumps not consistently setting cls kwarg to supplied encoder

### ISSUE THREAD

**Issue by alfinkel** [cloudant/python-cloudant#221]
All versions of python-cloudant and Python are affected.

We specifically allow for setting an `encoder` via key word argument when constructing a `client` instance.  The assumption is that this encoder would be set for all JSON encoding handled by the library, in other words all instances of `json.dumps` in the code should have a `cls` setting pointing to the encoder set on the client.  However, the use of the `encoder` is being used in some instances and not others.

We should fix this and update all occurrences of `json.dumps` to have the `cls` keyword argument set to the client encoder.

**Comment by cbartz** [comment]
There are still occurences of ``json.dumps`` where the custom encoder is not used: [_common_util.py#L78](https://github.com/cloudant/python-cloudant/blob/f21e190976dfba19ec9b4127fafa9f78b8fb3732/src/cloudant/_common_util.py#L78)

I used the ``endkey`` parameter with a JSON array,  and this resulted in an error because the encoder is not passed in [_common_util.py#L252](https://github.com/cloudant/python-cloudant/blob/f21e190976dfba19ec9b4127fafa9f78b8fb3732/src/cloudant/_common_util.py#L252).

This behaviour is a bit strange from a users perspective, because JSON structures are allowed as keys for a view, and apparently the "keys" parameter gets encoded with the custom encoder ([_common_util.py#L251](https://github.com/cloudant/python-cloudant/blob/f21e190976dfba19ec9b4127fafa9f78b8fb3732/src/cloudant/_common_util.py#L251)).
