### ISSUE TITLE
Automatically handle session renewal

### ISSUE THREAD

**Issue by rhyshort** [cloudant/python-cloudant#235]
Currently a user needs to handle the starting of a new session when theirs expires by either creating a new client, or calling `client.session_login`. What we should do is handle this situation transparently to user and renew the session if we receive a response indicating the session has expired. And retry the user request and return the results.

**Comment by alfinkel** [comment]
@ricellis, @rhyshort, @emlaver, 

What are your thoughts on tracking the session start time as a client attribute and basing the refresh of the cookie auth on the difference between the time of a request and the session start time?  

Prior to honoring the request we would perform this check and if the difference is greater than a certain amount (lets say 23 hours) then we would perform the POST to the _session endpoint to refresh the cookie auth before proceeding to handle the original request.  This could all be managed via a kwarg passed in when constructing the client so the default behavior can remain the same as it is now.  This would be a really simple solution since all of the classes that require an `r_session` currently already return it via a function with the `@property` decorator.  So the necessary code to do this comparison already has a convenient home.  I think the overhead would be relatively small to perform the time comparison prior to each request and a user of the library would have to expressly ask for this behavior via the additional keyword argument so they could/would be aware that they are asking for additional "reconnect" functionality that has some overhead.

Let me know your thoughts.

**Comment by smithsz** [comment]
Hi, I just pushed up some work I did last week for this. We ran into the bug in rebal2.
I was contemplating running the method call through a wrapper. If any request returns a `401` response then we check the cookie is still valid. If it is valid then just return the response as is. If not, issue a `login()` and retry.

The couchdb logs for a db create with an expired cookie would look something like this:
```
11:09:28.207 [notice] a1aa5eaded 127.0.0.1 localhost:5984 PUT /newdb1 401 ok 1
11:09:28.219 [notice] b21dc6126f 127.0.0.1 localhost:5984 GET /_session 200 ok 0
11:09:28.222 [notice] 431c61ed95 127.0.0.1 localhost:5984 POST /_session 200 ok 1
11:09:28.227 [notice] 2957c1a12a 127.0.0.1 localhost:5984 PUT /newdb1 201 ok 67
```

**Comment by rhyshort** [comment]
@alfinkel I wouldn't want to rely on the user getting the cookie timeout right, plus if a request is made and the cookie is near expiration, Cloudant should send a `Set-Cookie` header to update what we have.  So I think its easier and less error prone, to check the response like the other libs and login and retry, we can turn this on and off via kwargs if we should keep the current behaviour.

**Comment by rhyshort** [comment]
@smithsz Thats sort of what the other libraries do, quick question, why not check the response body for the tell tale `reason: session expired` in the response body when a 401 is encountered?

**Comment by rhyshort** [comment]
Need more coffee ☕️  this morning our other libs eg swift check for `error: credentials_expired`. Here is how Swift handles it: https://github.com/cloudant/swift-cloudant/blob/master/Source/URLSession.swift#L258-L262

**Comment by ricellis** [comment]
I'd prefer to follow the similar approach to the other libraries as @rhyshort says we should make use of the `Set-Cookie` response header to slide forward the sliding window and the other 401/403 response codes to handle the expiry cases.

**Comment by smithsz** [comment]
The `"error":"credentials_expired"` message was a dbcore thing. That's gone in dbnext (and never existed afaict in couch land). You just get the usual `"error":"unauthorized"` message.
