### ISSUE TITLE
Change default behaviour to automatically renew in next major version

### ISSUE THREAD

**Issue by ricellis** [cloudant/python-cloudant#241]
#235 (via #239) introduced the `auto_renew` option. To maintain compatibility with previously released versions of 2.x it defaults to `False`. Going forwards we should default to `True`.

So we should flip the default at the next major version change.

- Cloudant (python-cloudant) version(s) that are affected by this issue.
    - 2.3.0 < 3.0.0
- Python version 
    - N/A
- A small code sample that demonstrates the issue.
```python
# To get auto_renew behaviour in 2.x
CouchDB(..., auto_renew=True) 
# Suggesting on by default for 3.x
CouchDB(...)
```

**Comment by alfinkel** [comment]
We might want to consider making the `connect` option default to `True` as well as part of the next major version change.  Currently it is `False` to preserve the previous behavior of having to explicitly `connect()`.  Changing both the `connect` and the `auto_renew` options to `True` ensures that as soon as a client is constructed it is ready to handle requests and session auth renewal will be handled behind the scenes by the library.

**Comment by rhyshort** [comment]
If we are going to make auto-connect the default, is it worth keeping the connect method?

**Comment by alfinkel** [comment]
I think that all depends on how disruptive we want to be with a major release.  Obviously we want current users of the library to upgrade to our latest release but if we remove the `connect` method that could be a pretty big show shopper for a user out there that has `connect` used throughout their code.  If we have a significant amount of folks chosing not to upgrade then we may likely have to support two versions of the library.

Actually a better question might be whether we want to remove the `auto_renew` option and just have auto renewal of session auth be the way the library functions.  This wouldn't affect any current users from a coding perspective because any code passing `auto_renew` to a client constructor would simply be ignored.  So we'd be providing major release behavioral changes without much "major" disruption to current user's code bases.

**Comment by rhyshort** [comment]
I think making so auto renew is non-configurable  and set to `True` would be the thing to do. It would bring it into line with other libs where renewals are done automatically. it wouldn't make much of an impact to codebases and it would mean that the user doesn't have to deal with session expiry themselves. Although that all depends on users not having complex code for handling 401s.


For `connect` I do see your point, and I don't think we should get into the position where we support to versions (ala python itself), so switching the option for `connect` to true, but leave it configurable is probably the thing to do.

**Comment by ricellis** [comment]
We won't change this here.

Our new [cloudant-python-sdk](https://github.com/IBM/cloudant-python-sdk/)(beta) automatically connects and renews for the cases where the session cookie expires.
