### ISSUE TITLE
Some tests not cleaning up databases

### ISSUE THREAD

**Issue by ricellis** [cloudant/python-cloudant#248]
I've seen 170+ test databases left behind on the test server with names of the form `db-03d4d6a9-4ccf-4cee-bc67-6ab9dc33121b` that come from python-cloudant. Clearly under some circumstances the databases are not cleaned up, we need to find and fix that.

**Comment by emlaver** [comment]
I've run several tests against all the python modules and have a branch with some logging to see if any databases are left over from Jenkins builds.  Currently, I don't see any databases left over.  It's possible that the test databases left over were from a WIP branch.

**Comment by ricellis** [comment]
I also noticed that they were not present after a clean run when looking into another issue recently. I wondered if there were some failure cases that could cause them to be left behind, but I haven't had a chance to investigate further.

**Comment by emlaver** [comment]
After additional testing, there are databases left over from `test_retrieve_replication_state`.  I was using the `signal` module to timeout any test that took longer than 45 seconds.  In previous builds, the `test_retrieve_replication_state` would fail because it takes longer than 45 seconds to complete.  After reverting the commit with `signal`, the test now passes but two databases were left behind.
