### ISSUE TITLE
security_document['Cloudant']['nobody'] = ['_reader']   >>> KeyError: 'Cloudant'

### ISSUE THREAD

**Issue by snowch** [cloudant/python-cloudant#261]
I'm trying to follow the example https://python-cloudant.readthedocs.io/en/latest/security_document.html#cloudant.security_document.SecurityDocument to update a security document on a Cloudant database on bluemix.

- Cloudant (python-cloudant) version(s) that are affected by this issue : cloudant==2.3.0
- Python version : Python 3.4.3
- A small code sample that demonstrates the issue:

```
>>> USERNAME="xxxx"
>>> PASSWORD="xxxx"
>>> ACCOUNT_NAME="xxxx"
>>> from cloudant.client import Cloudant
>>> from cloudant.security_document import SecurityDocument
client = Cloudant(USERNAME, PASSWORD, account=ACCOUNT_NAME)
client.connect()
session = client.session()
>>>
>>> 
>>> db = client['moviedb']
>>> with SecurityDocument(db) as security_document:
... 	security_document['Cloudant']['nobody'] = ['_reader']
...
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
KeyError: 'Cloudant'
...
>>> with SecurityDocument(db) as security_document:
... 	security_document['cloudant']['nobody'] = ['_reader']
...
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
KeyError: 'cloudant'
```

**Comment by alfinkel** [comment]
I suspect that your problem is due to the fact that your security document is probably empty and there is no "Cloudant" or "cloudant" field.  One thing to keep in mind is that most of the classes provided by this library are subclasses of `dict` so ultimately they will all behave like a dictionary.  I suggest changing your security document manipulation to something like:

```python
with SecurityDocument(db) as security_document:
    security_document.update({'cloudant': {'nobody': ['_reader']}
```

which will update the security document to add a "cloudant" field and assign the "nobody" `dict` to it.

**Comment by snowch** [comment]
Thanks @alfinkel.  Is it worth updating the documentation to show this approach?

**Comment by alfinkel** [comment]
I thought about that but right now I am thinking that the answer is no because the docs are written based on the understanding that a user of the library has experience with Python.  The problem you experienced is not so much an idiosyncracy of the library but a behavior of the Python `dict` type.  The docs do show that the SecurityDocument is a subclass of `dict` so I think that should make it clear that a `KeyError` using a SecurityDocument object is due to the key in question being not found.

**Comment by snowch** [comment]
I think the issue for me is that I wasn't expecting the security document to be empty, which is why I reported this as a defect.  I haven't used this API for quite a while, so of course this is user error.   However, I'm a believer that if we can help users avoid misunderstandings by improving the documentation, then we probably should.

**Comment by alfinkel** [comment]
I agree with you about improving the documentation whenever possible.  It's just that I'm not certain whether adding the `.update(...)` example would be helpful in this case.  Just like the current example raising a `KeyError` when the "Cloudant" field is missing in the document dictionary is a Python `dict` behavior, using the update dict method in the way that I presented to you as an alternative would have some odd results for a security document that had content already in it.  For example:

```python
security_document = { 
  "cloudant": {
    "foo": ["_admin", "_reader", "_writer", "_replicator"], 
    "bar": ["_reader", "_writer"], 
    "nobody": []
  }
}
security_document.update({"cloudant": {"nobody": ["_reader"]}})
```
 would update the security_document to `{'cloudant': {'nobody': ['_reader']}}` and remove all the other permissions for `foo` and `bar` which I don't think is the desired result.

Both approaches behave exactly as one would expect a Python dict object to behave.

I chose the current example because it seemed to be the most generic approach to showcase the SecurityDocument context manager while staying true to the general structure of a Cloudant security document.

I'm completely onboard with adding clarity to the docs, I'm just not sure of what to add here that would work better than what we have right now.  After all this example is meant to showcase the SecurityDocument context manager and not how to populate the contents of the SecurityDocument dictionary.

One thought would be to remove the population of the contents altogether and just replace them with a comment like:

```python
# Upon entry into the security document context, fetches the security
# document from the remote database, if it exists. Upon exit from the
# context, saves the security document to the remote database with
# changes made within the context.
with SecurityDocument(database) as security_document:
    # The security document is fetched from the remote database
    # Changes are made locally
    ...
    # Populate security document dictionary accordingly
    ...
    # The security document is saved to the remote database
```

Let me know if you have other ideas.

**Comment by snowch** [comment]
Ah, I see.  I made an incorrect assumption that update() was doing a kind of merge.  It's all clear now after looking through the python stdlib docs.

I think it's useful to leave the example as it currently is.  I agree that adding code for checking the dict keys exist will start looking messy.

Thanks for taking the time to explain!
