### ISSUE TITLE
Investigate managing a shared session cookie

### ISSUE THREAD

**Issue by emlaver** [cloudant/python-cloudant#275]
@snowch: should we have the ability to create the cloudant client instance in the http handler and behind the scenes the cloudant python library manages a shared session cookie?
Other thoughts:
How can we share the cookie within the library?  Maybe we need to be able to pass a cookie in as a parameter to cloudant client?

**Comment by snowch** [comment]
I was wondering whether the library provided a CookieStore class that library users create as a global instance.  That could be passed to the cloudant client constructor:

```
  cookies = CookieStore()
  adapters = ...

  @app.route('/')
   def hello_world():
      client = Cloudant(USERNAME, PASSWORD,
                                    url='https://acct.cloudant.com',
                                    auto_renew=True,
                                    connect=True,
                                    cookie_store=cookies
                                    adapters=adapters)

      # assume we can't/don't want to cache (e.g. Redis) the status doc 
      db = client['mydb']
      doc = ['status'].fetch()
      return doc
```

The cloudant client would attempt to retrieve the session cookie from the cookie store.  If the store doesn't contain a cookie, or it is about to expire within a configurable threshold, the cloudant client would make a call to cloudant to get a new cookie and would save it in the cookie store.

The cookiestore is needed because cloudant python needs somewhere to store/retrieve the session cookie in between executions of hello_world().   The cookieStore will need to be threadsafe and should store the latest session cookie.

**Comment by ricellis** [comment]
We're not doing ehancements here.
Our new [cloudant-python-sdk](https://github.com/IBM/cloudant-python-sdk/)(beta) has locking around session token exchanges to ensure a client instance shared between multiple threads uses the same token across all threads and obtains and renews it only once per session lifetime.
