### ISSUE TITLE
Implement `.ping()` endpoint

### ISSUE THREAD

**Issue by smithsz** [cloudant/python-cloudant#339]
See https://console.bluemix.net/docs/services/Cloudant/api/account.html#ping.

Current workaround:
```python
from cloudant.client import CouchDB
client = CouchDB(connect=True, ...)
print client.r_session.get(client.server_url).json()
```

**Comment by ricellis** [comment]
This was already fixed by #379 which added a `metadata()` function.

Our new [cloudant-python-sdk](https://github.com/IBM/cloudant-python-sdk/)(beta) has support for both:
* [`get_server_information()`](https://cloud.ibm.com/apidocs/cloudant?code=python#getserverinformation)
* [`get_up_information()`](https://cloud.ibm.com/apidocs/cloudant?code=python#getupinformation)
