### ISSUE TITLE
Feature Proposal: Compaction

### ISSUE THREAD

**Issue by SteinRobert** [cloudant/python-cloudant#454]
Since this is not a bug, more a request/proposal I would be willing to help with, I hope it's okay this does not follow the issue template structure.

I did not find any method to trigger compaction for a database. Is there a reason for it? Do you think it would be worth implementing it? If yes, I'd be happy to help.

**Comment by emlaver** [comment]
@SteinRobert adding the compaction endpoint is low on our priority.
You can use the session object to make requests against this endpoint.  For example:
```
client = CouchDB(...setup connection...)
db_name = ...
response = client.r_session.post(
  '/'.join([client.server_url, db_name, '_compact']))
```

**Comment by ricellis** [comment]
We're not adding new features here.
Our new [cloudant-python-sdk](https://github.com/IBM/cloudant-python-sdk/)(beta) also doesn't have a specific operation for calling compaction because [compaction is automatic](https://docs.couchdb.org/en/stable/maintenance/compaction.html#compact-auto) since [CouchDB 3.0.0](https://docs.couchdb.org/en/3.1.1/whatsnew/3.0.html#id1).
