### ISSUE TITLE
Additional indexes being added to design doc handler?

### ISSUE THREAD

**Issue by bradwbonn** [cloudant/python-cloudant#48]
Right now it looks like the ddoc handler can only manage secondary indexes.  Are things like Lucene, CQ and Geo coming too?

**Comment by alfinkel** [comment]
Yep.  Working on that right now actually, but to be clear since the DesignDocument is really just a dictionary on steroids, any design document content can be managed via a DesignDocument object right now.  It is true that there are no convenience methods available in the DesignDocument class for anything other than views currently. That will likely not change once we add support for query.  Instead index management will likely be done via a database object rather than a DesignDocument object.  We can chat on slack in greater detail if you'd like.

**Comment by alfinkel** [comment]
See #39 and #40 for tracking.

**Comment by bradwbonn** [comment]
Got it!  That makes sense to put it on the database object anyway, since design documents are more of a technicality of how the database creates indexes.  I imagine that I could probably just use Document as well, just specifying the _id to start with "_design/".  Since we have to do that with the DesignDocument object anyway, it's not a far stretch.

**Comment by alfinkel** [comment]
Correct.
