### ISSUE TITLE
On database.get_view_result() group_level is expecting type 'basestring'

### ISSUE THREAD

**Issue by bradwbonn** [cloudant/python-cloudant#55]
Shouldn't this accept an integer since it's going to be set as a numeric value?
`cloudant.errors.CloudantArgumentError: Argument group_level not instance of expected type: <type 'basestring'>`

**Comment by bradwbonn** [comment]
Actually I think this is broken altogether.  The group_level parameter gets passed as a string in the URL with quotes, and so it comes back with an error 400:

    File "/Library/Python/2.7/site-packages/cloudant/result.py", line 182, in __getitem__
        data = self._ref(key=key, **self.options)
    File "/Library/Python/2.7/site-packages/cloudant/views.py", line 238, in __call__
    resp.raise_for_status()
    File "/Library/Python/2.7/site-packages/requests/models.py", line 837, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
    requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://bradwbonn.cloudant.com/scandb-1450286616/_design/scanresults/_view/targetfiles?startkey=%5B%224e8e0b111e57ce742035f94985198b5f%22%2C+null%2C+null%5D&endkey=%5B%224e8e0b111e57ce742035f94985198b5f%22%2C+%7B%7D%2C+true%5D&reduce=true&group_level=%223%22&key=%22rows%22

**Comment by bradwbonn** [comment]
### A better summary
#### If I run 
            result = scandb.get_view_result(ddoc,
                                            view,
                                            startkey=start_key,
                                            endkey=end_key,
                                            group_level=3,
                                            reduce=True
                                            )['rows'][0]

Result is 

    File "/Library/Python/2.7/site-packages/cloudant/result.py", line 182, in __getitem__
    data = self._ref(key=key, **self.options)
    File "/Library/Python/2.7/site-packages/cloudant/views.py", line 236, in __call__
    params = python_to_couch(kwargs)
    File "/Library/Python/2.7/site-packages/cloudant/result.py", line 79, in python_to_couch
    raise CloudantArgumentError(msg)
    cloudant.errors.CloudantArgumentError: Argument group_level not instance of expected type: <type 'basestring'>

#### If I run

            result = scandb.get_view_result(ddoc,
                                            view,
                                            startkey=start_key,
                                            endkey=end_key,
                                            group_level=str(3),
                                            reduce=True
                                            )['rows'][0]

I get: 

    File "/Library/Python/2.7/site-packages/cloudant/result.py", line 182, in __getitem__
    data = self._ref(key=key, **self.options)
    File "/Library/Python/2.7/site-packages/cloudant/views.py", line 238, in __call__
    resp.raise_for_status()
    File "/Library/Python/2.7/site-packages/requests/models.py", line 837, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
    requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://bradwbonn.cloudant.com/scandb-1450286616/_design/scanresults/_view/targetfiles?startkey=%5B%224e8e0b111e57ce742035f94985198b5f%22%2C+null%2C+null%5D&endkey=%5B%224e8e0b111e57ce742035f94985198b5f%22%2C+%7B%7D%2C+true%5D&reduce=true&group_level=%223%22&key=%22rows%22

**Comment by alfinkel** [comment]
Yep.  That is a bug for sure.  The group_level is mis-typed in our result module ARG_TYPES.  It should be set to `(int, types.NoneType)` but is currently set to `basestring`.  We'll get that in the queue to fix.

BTW, your call to `.get_view_result(...)['rows'][0]` won't ever work because that method returns a `Result` which provides you with a pythonic way of slicing and iterating through the results.  It processes the ['rows'] part automatically.  So adding it again in your code will likely cause an error or at the very least to not return anything.  Either remove the `['rows'][0]` from your call or use the `.get_view_raw_result()` method instead which returns the raw JSON response.  

Specifically to get the first Result you would do `result[:1]`.

Take a look at the Getting Started section on using [results](http://python-cloudant.readthedocs.org/en/latest/getting_started.html#dealing-with-results) for more detail and the [Result](http://python-cloudant.readthedocs.org/en/latest/result.html) section also has some good examples.

**Comment by bradwbonn** [comment]
Great to know, thanks!  I was trying to wrap my head around how to use the Result class.  Once it's patched, I'll experiment more with it.  For now I'll use .get_view_raw_result() as before.

**Comment by bradwbonn** [comment]
Looks like .get_view_raw_result() is also expecting a string. :(

**Comment by alfinkel** [comment]
Assuming you mean for group_level... Yes the bug is not Result specific, the code exists in the results module.  Now that I re-read my earlier response, I can see how that would be confusing.  

My comment about `.get_view_raw_result()` was unrelated to the group_level bug.  I only meant that if you wanted to process your own non-Result wrapped output as it looked like your code was attempting to do then you should use `.get_view_raw_result()`.  

If you find that must use the group_level argument then I would suggest that you use the endpoint access directly to generate the output.

**Comment by bradwbonn** [comment]
Yes, for group_level, and for the moment that's the plan.  :)  Thanks
